
version: '3'
services:

  db:
    
    image: mysql:5.7 
    
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: 'db'
    environment:
      MYSQL_ROOT_PASSWORD: ${BD_PASSWORD}
      MYSQL_DATABASE: ${BD_DATABASE}
      TZ: America/Sao_Paulo

    ports:
      - ${BD_PORT}:${BD_PORT}

    volumes:
      - ./bd:/var/lib/mysql

  app:
    
    container_name: eliper-api
    
    restart: always

    build: .

    ports:
      - ${PORT}:${PORT}
      
    depends_on:
      - db

    command: yarn start

  