version: '3'
services:
  mysqlsrv:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
       MYSQL_ROOT_PASSWORD: "${BD_PASSWORD}"
       MYSQL_DATABASE: ${BD_DATABASE}
    ports:
      - ${BD_PORT}:3306
    volumes:
      - D:/bd-data/MySQL:/var/lib/mysql

  