version: '3'
services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql_container

    environment:
       MYSQL_ROOT_PASSWORD: "172010joao"
       MYSQL_DATABASE: tcc
    ports:
      - "3306:3306"
    volumes:
      - D:/bd-data/MySql:/var/lib/mysql